# Generated by Django 2.2.14 on 2020-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('test_type', models.CharField(choices=[('RT', 'RT-PCR'), ('SO', 'Sorologia'), ('AG', 'Teste Rápido - Antígenos'), ('AC', 'Teste Rápido - Anticorpos')], max_length=2)),
                ('test_result', models.BooleanField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
